### ISSUE TITLE
RFC: Config objects instead of arrays in CakePHP 4

### ISSUE THREAD

**Issue by burzum** [cakephp/cakephp#10866]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 4.0

### What you did
Lot's of mistakes in these aweful huge configuration arrays in many places in CakePHP...

### What happened
Got annoyed by the fact the arrays are huge and sometimes deeply nested.

### What you expected to happen
Being slapped by the framework with an exception if I made a typo in the 3rd level of a nested configuration array.

## Objects!? Why not arrays?

You should use objects instead of arrays because:

* An array can't be type checked if it really is the intended config
* It is easy to have typos in config arrays
* The configuration is separated from the class unlike when using `InstanceConfigTrait`
* Getters and setters (IDE auto-completion, strict types possible)
* Optional bonus: An array doesn't bring easy validation of config data with it

## Sample Implementation

https://github.com/burzum/cakephp-config-objects

I would like to see CakePHP 4 dropping config arrays in favour of objects.

**Comment by markstory** [comment]
Sounds like an interesting idea. Would you see configuration objects being used everywhere? How woukd that work with open option arguments like those used in helpers?

**Comment by ionas** [comment]
Can you show an example of day to day use how you would use Config class to setup say `HtmlHelper::link('label', $urlOptions, $linkOptions)` or `$tbl->find('withFoo', $options)`?

- I would like to see strict options validation. This should include that there should be Exceptions in debug and Warnings in production mode for options that are not supported (anymore). Typos or outdated keys should not pass. Also values of wrong types should not pass.
- I don't want to be spoiled by more verbose getter/setters. It is okay to pass a Config object, but filling it should always be easy through hash keys/values and even nesting those. When passing arrays to its constructor there should be a standardized way on how to validate options array/tree structure (aka hash keys and sub trees) as well as leaf value data types (string, int, float, is_a, in_list; mixed(a,b)). Somehow this reminded me of GraphQL.

**Comment by burzum** [comment]
You've picked exactly the cases I have not intended to use it for. But OK:

```php
$this->Html->link('foo', '/', (new LinkOptions)
   ->setClass(['btn', 'btn-default']);
   ->setData('foo', $value')
));
```

For the find options it would work only with generic set/get:

```php
$query->find('foo', (new Config)
->set('foo', 'bar')
->set('something', 'else')
);

**Comment by ionas** [comment]
... And then day-to-day I am mostly using options for finders, and within Html- and FormHelper.

This is what I fear (sure things can be improved a little bit here and there):
```php
<?= $this->Html->link('<button>Edit Post</button>', [
    'prefix' => 'Admin', 'plugin' => 'MyPlugin', controller' => 'Posts', 'action' => 'edit', $id, 'q' => [
        'redirect' => ['prefix' => 'Admin', 'plugin' => 'MyPlugin', 'controller' => 'Posts', 'action' => 'index']]],
    ['escape' => false]
) ?>
```

### VS

```php     
<?= $this->Html->link('<button>Edit Post</button>',
        $this->Html->newRouterOptions()
            ->setPrefix('Admin')
            ->setPlugin('MyPlugin')
            ->setController('Posts')
            ->setAction('edit')
            ->setParams([0 => $id]),
            ->setQueryStringOptions([
                'redirect' => $this->Html->newRouterOptions()
                    ->setPrefix('Admin')
                    ->setPlugin('MyPlugin')
                    ->setController('Posts')
                    ->setAction('index')]),
        $this->Html->elementOptions()
            ->setEscape(false)
) ?>
```

* * *

What I am looking for is being able to define a schema for how options look like so that the type is strict and anything beyond that schema would fail.

- It should allow definition of what kind of structure can go in (aka array, nested array)
- which keys there are on what level
- what type of variable an option key can bind to
- for enum options which value one key can bind to
- if an option key (or an option sub-tree) is optional or not
- I am not sure about defaults, if they should be part of the schema or not
- It should possibly be stateless, aka just a rigid schema no checks (say you could check if a given id actually exists, but that's not the job of the config data type, but the function processing the config data type)

p.s.: The same kind of validator could possibly be used to validate query strings coming from the user.

**Comment by inoas** [comment]
Ref https://github.com/cakephp/cakephp/pull/10887 where I fear the same.

**Comment by robertpustulka** [comment]
@inoas the new API should be opt-in in my opinion. You would continue to use array config, all the validation etc would be done internally.

The options factory method could take an array as an argument so you could configure your link like this:
```php
<?= $this->Html->link('<button>Edit Post</button>', $url, ['escape' => false]) ?>
```
or like this:
```php
<?= $this->Html->link('<button>Edit Post</button>', $url,
$this->Html->linkOptions(['escape' => false])->addClass('foo') ?>
```

**Comment by inoas** [comment]
@robertpustulka there is little gain if it is optional. Also the validation via setters is tainted as it cannot validate "at once". Once the whole $options pattern is set (e.g. is about to be consumed) it needs to be validated and the setters/getters cannot do that because they are about one value at a time.

**Comment by burzum** [comment]
@ionas the setters will fail immediate with an InvalidArgumentException and in php7.1 we can use types. No extra validation needed then.

**Comment by mamchenkov** [comment]
I'd like to second @ionas point on the schema validation.  We have recently adopted JSON Schema validation for our configurations and that change alone was worth all the trouble migrating the code towards it.  One of these days, we'll also apply the documentation generator on the JSON Schema (like [docson](https://github.com/lbovet/docson) or something similar), and the world will be awesome once again :)

**Comment by inoas** [comment]
@burzum setters are a weak design pattern for validation of complex structures.
Setters should not inspect the holistic pattern but only their single value. They cannot enforce schema validity. If you make them do that you have to enforce order of calling - e.g. you can only call `setParams()` or `setPass()` if you before that at least called `setController()` or `setAction()`.

In comparison validating data structures through schema allows to cover all stateless validation requirements. Any stateful (such as does the $id in params/pass actually exists as a record) are up to business logic implementation.

@mamchenkov can you supply an example. That sounds really nice!

**Comment by mamchenkov** [comment]
@inoas (sorry for a typo in your name in a previous comment - corrected) 

Here is an example of what we are doing:

1. [JSON Schema](https://github.com/QoboLtd/cakephp-utils/blob/master/src/ModuleConfig/Parser/Schema/config.json) for the `config.ini` file.  (We'll be moving it to JSON real soon now).
2. [Config Parser](https://github.com/QoboLtd/cakephp-utils/blob/master/src/ModuleConfig/Parser/Ini/ConfigParser.php), which does a bit too much now, because of the INI format.  Once moved to JSON, none of this will be necessary.
3. [Config Parser Tests](https://github.com/QoboLtd/cakephp-utils/blob/master/tests/TestCase/ModuleConfig/Parser/Ini/ConfigParserTest.php)
4. [Another plugin relying on this functionality](https://github.com/QoboLtd/cakephp-csv-migrations/blob/master/src/ConfigurationTrait.php#L66)

Let me know if you need more :)

**Comment by josegonzalez** [comment]
You could probably create a `ConfigArrayAccess` class that had automagic setters and getters. Would retain compatibility with our existing stuff - array access - and would be extensible to support any config - automagic getters and setters.

**Comment by burzum** [comment]
@ionas I disagree. JSON schema is a complete unnecessary bloat for most of the cases. It's a great way to describe a RESTful JSON API but IMHO just a huge bloat for simple configuration objects. We also have the built in validation we could use plus more strict types in 4.0 so that we don't need to check for them in the method itself.

**Comment by lorenzo** [comment]
I would like to see this for configuration, but not for every `$options` parameter in the core.

**Comment by burzum** [comment]
@josegonzalez I've updated the plugin and added `\ArrayAccess.`

**Comment by josegonzalez** [comment]
@burzum also maybe relevant: http://php.net/manual/en/migration71.new-features.php#migration71.new-features.iterable-pseudo-type

**Comment by inoas** [comment]
I watched @markstory's take on getting to 4.0 from last cakefest and the articulated goal is to have stricter interfaces. As far as I understood, the goal is to have a framework that throws much more helpful errors at the user and much earlier - pretty much like Elm does.

> What you did
> Lot's of mistakes in these aweful huge configuration arrays in many places in CakePHP...

JSON Schema was only meant as a reference. Any other declarative way to say what $options structure/s is/are valid helps. Here I hope we can help day-to-day developers with:
- missing hash-keys to have a consumption-ready configuration/options
- miss-typed hash-keys
- correct hash-keys at the wrong place in the options structure
- out-dated hash-keys
- hash keys assigned to unexpected data types
- static enums
- legit optionality
- default values

The options/config structure should easily be validated. We can validate everything that does not need to know about application/database state.

Once this the validation set is passed the `$options` can be relied on and just be used instead of using `array_key_exists()` (or isset/empty).

A declarative schema is also kind of self documenting. You take a look at the code (not the docblock) and you immediately know what you have to set / what you can set and in what way.

As for your quest to compare to other frameworks: CakePHP is heavily using `$options` arrays as part of its design because it inherited the concept from Ruby on Rails which uses atoms/symbols.
If I wanted CakePHP to be like Symfony or Laravel, I would pick those frameworks instead.

**Comment by jeremyharris** [comment]
After discussing this a bit with @ionas in slack, I like the idea of a schema-type way of validation. Similar to how the ConsoleOptionParser rejects unknown options, the validator would do the same (thus catching typos). This of course doesn't solve the discoverability issue, but IMO the more important one is that options are correct.

**Comment by rordi** [comment]
I would also love to see the possibility to save parameters in separate files (such as YML), so that I do not need a whole config file per environment, but can use one common config file and inject one environment-specific parameter file with the variables at build time.

**Comment by markstory** [comment]
@rordi You can already do this by loading environment specific config files during your application bootstrap, or using [environment variables](https://book.cakephp.org/3.0/en/development/configuration.html#environment-variables).

**Comment by inoas** [comment]
@rordi that's already possible.
```php
// in bootstrap.php
try {
    Configure::load('app_local', 'default');
    Configure::load('env_local', 'default');
} catch (\Exception $e) {
    exit($e->getMessage() . "\n");
}
```
And for YAML there are plugins for cakephp AFAIR.
There is also an env loader by @josegonzalez AFAIR.

**Comment by dereuromark** [comment]
So should we close this then?
Given that there is a plugin option now - and that this is most likely not ending up in the core anyway.
Also, there is now [CakeDto](https://github.com/dereuromark/cakephp-dto) as glue between those different things as clean object solution over arrays.
So, for now, that seems to cover most cases.

**Comment by dereuromark** [comment]
Yeah, so this wouldn't any time soon be able to get processed for core.
