### ISSUE TITLE
withStatus does not check if supplied status is valid

### ISSUE THREAD

**Issue by tuna-rootnet** [cakephp/cakephp#11677]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.11.
* Platform and Target: nginx/1.10.3 (Ubuntu), mysql  Ver 15.1 Distrib 10.0.33-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2, FriendsOfCake/Crud 5.3

### What you did
In any controller using Crud and methods mapped to the ViewAction, you can do `$this->Crud->execute()` and all is fine and well in the world. Place a `return` in front of the statement, and you get 502 Bad Gateway errors.
```
$this->Crud->mapAction('someWorkingMethod', 'Crud.View');
$this->Crud->mapAction('someBrokenMethod', 'Crud.View');

//working
public function someWorkingMethod() {
    $this->Crud->execute();
}

// crashing
public function someBrokenMethod() {
    return $this->Crud->execute();
}
```

### What happened
Through some digging, we found the statuscode in the response is null, gets transformed to 0 and nginx loses it. The statuscode being null originates from the ViewAction missing an index `api` in its defaultConfig. We encountered this problem after we updated to Crud 5.3, which now uses `$response->withStatus()` instead of `$response->statusCode()`. `withStatus()` does not check the provided status, which `statusCode` did.

### What you expected to happen
We expected our methods to simply return the response, instead of completely crashing. The statuscode should never become null.

**Comment by dereuromark** [comment]
Sounds to me like  Crud 5.3 should be fixed instead to properly pass a statusCode along into withStatus() as this method expects.
So `$status ?: $default` IMO.

**Comment by ADmad** [comment]
@dereuromark In general I think it would be better to add checks in `Response::withStatus()` and prevent it from accepting invalid status codes.

**Comment by tuna-rootnet** [comment]
Yes, we'll be creating an issue in the Crud repo as well, but it would not solve the problem that you can end up with invalid response status codes with the current code. It would seem logical to me that when statusCode() is deprecated and everyone needs to use withStatus(), it should still have the same functionality, only applied to middleware and stuff. If for whatever reason something gives an invalid response code, the Response class should provide a default. At the very least it should give a warning.

**Comment by dereuromark** [comment]
PR open.
