### ISSUE TITLE
Undefined variable: eTagMatches

### ISSUE THREAD

**Issue by shanept** [cakephp/cakephp#12536]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.5.17
* Platform and Target: PHP 7.3 on CentOS 7. CakePHP being consumed by 'passbolt' application.

### What you did
Upon enabling debugging output, I get the following notices, which then cause the remaining warnings:

```
Notice (8): compact(): Undefined variable: etagMatches [CORE/src/Http/Response.php, line 1887]
Notice (8): compact() [<a href='https://secure.php.net/function.compact'>function.compact</a>]: Undefined variable: timeMatches [CORE/src/Http/Response.php, line 1887]
Notice (8): compact() [<a href='https://secure.php.net/function.compact'>function.compact</a>]: Undefined variable: etagMatches [CORE/src/Http/Response.php, line 1887]
Notice (8): compact() [<a href='https://secure.php.net/function.compact'>function.compact</a>]: Undefined variable: timeMatches [CORE/src/Http/Response.php, line 1887]
Warning (512): Unable to emit headers. Headers sent in file=/srv/www/vendor/cakephp/cakephp/src/Error/Debugger.php line=850 [CORE/src/Http/ResponseEmitter.php, line 48]
Warning (2): Cannot modify header information - headers already sent by (output started at /srv/www/vendor/cakephp/cakephp/src/Error/Debugger.php:850) [CORE/src/Http/ResponseEmitter.php, line 148]
Warning (2): Cannot modify header information - headers already sent by (output started at /srv/www/vendor/cakephp/cakephp/src/Error/Debugger.php:850) [CORE/src/Http/ResponseEmitter.php, line 177]
```

### What happened
The following code is from Http\Response::checkNotModified. On the `compact` line, this actually expects that the variables to be compacted actually do exist. This is a poor variable existence check and causes the above notices to be output, which further break the application as it can no longer output headers.

```php
        if ($responseTag) {
            $etagMatches = in_array('*', $etags) || in_array($responseTag, $etags);
        }
        $modifiedSince = $request->getHeaderLine('If-Modified-Since');
        if ($modifiedSince && $this->hasHeader('Last-Modified')) {
            $timeMatches = strtotime($this->getHeaderLine('Last-Modified')) === strtotime($modifiedSince);
        }
        $checks = compact('etagMatches', 'timeMatches');
        if (empty($checks)) {
            return false;
        }
        $notModified = !in_array(false, $checks, true);
```

### What you expected to happen
No errors should be output.

### Proposed solution
I propose the following solution:

```php
        if ($responseTag) {
            $etagMatches = in_array('*', $etags) || in_array($responseTag, $etags);
        }
        $modifiedSince = $request->getHeaderLine('If-Modified-Since');
        if ($modifiedSince && $this->hasHeader('Last-Modified')) {
            $timeMatches = strtotime($this->getHeaderLine('Last-Modified')) === strtotime($modifiedSince);
        }
        if (!isset($etagMatches, $timeMatches)) {
            return false;
        }
        $checks = compact('etagMatches', 'timeMatches');
        $notModified = !in_array(false, $checks, true);
```

**Comment by markstory** [comment]
3.5 is no longer receiving big fixes. You will need to upgrade to 3.6 to get any fixes made to solve this.

We have #12488 open to update our test suites to run against 7.3 but we are waiting on travis ci to enable 7.3. Until that happens we won't be able to make much progress.

**Comment by shanept** [comment]
@markstory That's fair - however I checked the current codebase prior to posting the issue. It is still in the current codebase.
https://github.com/cakephp/cakephp/blob/master/src/Http/Response.php#L2066

**Comment by markstory** [comment]
@shanept Sure is. Like I said we haven't done any compatibility work for 7.3 as it isn't available yet in travis. My comment about 3.5 not getting bugfixes was to set expectations on which release would get a fix. Sometimes folks are expecting us to do releases of unsupported branches.

**Comment by shanept** [comment]
Ahh, I see.
Not a problem, thank you :)

**Comment by makamo** [comment]
PHP 7.3 is now available on Trusty and Precise (7.3.0RC3 aliased to 7.3) in non-sudo mode.

https://github.com/travis-ci/travis-ci/issues/9717#issuecomment-429564626

**Comment by ADmad** [comment]
Fixed in #12488

**Comment by infinitbility** [comment]
Explain Here Step by Step to solve the issue

https://infinitbility.com/undefined-variable-timematches-and-etagmatches-cakephp

**Comment by Maksoud** [comment]
Thank you shanept!

**Comment by Maksoud** [comment]
@shanept Thank you!

**Comment by nilsonpena** [comment]
> Fixed in #12488

Just upgraded to 3.10, and this error persists!!
Using php 7.4.3 here
Any ideia?

**Comment by markstory** [comment]
> Just upgraded to 3.10, and this error persists!!

How can I reproduce the error you're seeing?

**Comment by vnxbug** [comment]
> Explain Here Step by Step to solve the issue
> 
> https://infinitbility.com/undefined-variable-timematches-and-etagmatches-cakephp

This guide is not working for me

Only search : 

Only search

`$checks = compact('etagMatches', 'timeMatches');
        if (empty($checks)) {
            return false;
        }`

And replace with : 

`if (!isset($etagMatches, $timeMatches)) {
            return false;
        }
        $checks = compact('etagMatches', 'timeMatches');`

Working for me now !
