### ISSUE TITLE
Empty CAKEPHP session value prevents Session/AuthComponent from logging in users

### ISSUE THREAD

**Issue by mfn** [cakephp/cakephp#6053]
When the session Cookie `CAKEPHP` has an empty string as value or the value `0`, it seems the Session cannot be properly regenerated.

E.g. when using the AuthComponent: 
```PHP
    if (!empty($this->Auth->user('id'))) {
```
the user will never be authenticated because of this problem.

The interesting thing is, if you change the cookies value to `1` and submit a login request, it **will be regenerated** to a proper session ID and authentication works.

But the regeneration will not happen with an empty cookie value. In that regard, the "broken" session sticks to the user unless he restarted the browser (but some browser have the feature to not clear session if the tab is open, etc.).

This is independent of the Security component (we tested with and without).

We observes having an empty `CAKEPHP` cookie will in the Chrome browser. At this point we do not know why only this browser exhibited the problem "in the wild" so far. We can, however, reproduce this problem in any browser by just manually setting the cookie value to an empty string or `0`.

Our current workaround is to forcefully regenerated the session ID:
```PHP
    # $this->Session is the SessionComponent
    if (empty($this->Session->id())) {
      session_regenerate_id();
    }
```

It seems that in some place(s) using `empty()` checks on the session ID would cause this behavior (it's just a guess because an empty string and `0` exhibit the same problem), but I couldn't track the actual cause inside CakePHP so far :-/

This was tested with the latest CakePHP 2 version, 2.6.2 .

**Comment by mfn** [comment]
Not sure if it helps, but looking at [CakeSession](https://github.com/cakephp/cakephp/blob/08ed3c55fd04763a974fa4283457ca504395e86a/lib/Cake/Model/Datasource/CakeSession.php#L724):
```PHP
<?php
public static function renew() {
    if (!session_id()) {
        return;
    }
    if (isset($_COOKIE[session_name()])) {
        setcookie(Configure::read('Session.cookie'), '', time() - 42000, self::$path);
    }
    session_regenerate_id(true);
}
```
Maybe regenerating the session id should be independent whether the current one is valid or not.

If I make session_regenerate_id() always being executed, it works for me too.

**Comment by markstory** [comment]
session_id() is documented as returning a string, and an empty string when no session exists. I can't think of a reason why removing the session_id check would be a problem. I suspect it is primarily an optimization.

**Comment by mfn** [comment]
As I tried to outline, if the users `CAKEPHP` cookie has an empty value, equaling to an empty string, this value "sticks" and the user never gets a new/proper/regenerated cookie. He's basically stuck in that state.

You can simply try it yourself. Use FF/firebug/whatever, edit your `CAKEPHP` cookie and replace it with either an empty string or the string `0`. From my experience, from that point on you shouldn't be able to login anymore.

**Comment by ADmad** [comment]
> if the users CAKEPHP cookie has an empty value, equaling to an empty string,...

Why would a session cookie's value be empty?

**Comment by johannesnagl** [comment]
> Why would a session cookie's value be empty?

we have no idea why and when this is happening. but couple of users were complaining the last couple of weeks. as @mfn pointed out: only chrome users until now. 

so there's definitely a scenario, where users happen to end up with such a value in the CAKEPHP cookie.

**Comment by AD7six** [comment]
> so there's definitely a scenario, where users happen to end up with such a value in the CAKEPHP cookie.

That sounds like the problem to investigate/fix - the session cookie being present but empty is a _symptom_ or something else not working correctly.

**Comment by AD7six** [comment]
> I can't think of a reason why removing the session_id check would be a problem

@markstory If there isn't already a session - that's going to start one.

**Comment by markstory** [comment]
Well the method is trying to renew the session. Starting the session doesn't seem unreasonable.

**Comment by mfn** [comment]
> That sounds like the problem to investigate/fix - the session cookie being present but empty is a symptom or something else not working correctly

We absolutely agree! Thing is, to our best knowledge we're using the cake components (session, auth) as intended; we don't mess directly with the cookie at all. We do not know when this happens, just that it happens.

Since we can't pin down that problem, but we're controlling the server, we're attacking it from that side for now, ensuring there's always a valid session.

However I completely understand the concerns regarding a forced session creation in case there wasn't any and on top the problem that `session_id()` alone can't differentiate between no session started or simply invalid session id value received.

**Comment by markstory** [comment]
Fixed with #6209

**Comment by mfn** [comment]
Just wanted to mention: my initial reporting laid out two cases in which the session regeneration doesn't work. Empty string `""` and `"0"`. The applied fix only handles the `0` case. An empty string still fails to properly re-generate a new session and leaves affected users in limbo.

**Comment by lorenzo** [comment]
@mfn according to http://php.net/session_id an empty string means that there is no session. A session without a valid id cannot be re-regenated

**Comment by mfn** [comment]
@lorenzo I'm aware of this. However, if I use something like Firebug and set `CAKEPHP` to an empty string, I can reproduce the limbo case.

As someone else mentioned, it is probably true that the source shall be found why it gets set to an empty string in the first place. It's a yet unsolved mystery for us and quite a difficult to track (we aren't doing manual mucking with cookies).

I just wanted to mention this, in case someone else has this exact problem too.

**Comment by lorenzo** [comment]
The reason is probably because you have the `checkAgent` session setting set to `true`. Try setting it to `false`

**Comment by doctorfox** [comment]
The empty session id tends to happen more often with users accessing the site using some form of local proxy server.

**Comment by mfn** [comment]
Interesting. We stopped investigating further. The official fix did not work for us in all cases we observed, thus to this tail we've an additional workaround to use.

**Comment by doctorfox** [comment]
I also tried fixing this.
At first I thought it was because of the session engine I was using (database sessions). But switching to basic file sessions did not change this.
So I looked at the way the sessions were being created and lost.
If the user visit the page when she is already logged in, then there seems to be no problem.
However, if the user comes in for the first time not logged in then this is how it happens (based on my little understanding).

1. User submits log in details.
2. CakePHP authenticates the log in and if it is valid, then log in.
3. Next, CakePHP creates the session with a new session id and sends this with the cookie.
4. The user appears to be logged momentarily but is immediately logged out.

Now normally the browser should send the next request and include the session id, but instead for these users, what I see is a value of "deleted" as the session id.
This causes the session to be lost and the user gets logged out immediately after logging in.
The session was created normally as I could see the correct session id was created on the server.
But for the next request I received from the user the session id had been replaced with the value "deleted".
The problem is I don't understand why this happens only with these proxy users.
