### ISSUE TITLE
Use of EntityTrait->_mutated could be optional or disabled for virtual properties

### ISSUE THREAD

**Issue by adayth** [cakephp/cakephp#6574]
Storing of magic _get() function calls of entities in inner _mutated array was giving me a lot of headaches figuring was where happening inside. Maybe should be at most advertised in documentation.

My case of use is the next:

I'm developing a cart checkout process and I storing entities in session to represent the status of the cart, checkout, cart items, items selectable options, etc. 

The main reason of my problems is that I storing entities in session temporary, until I can save all at the end of the process.

I set some virtual properties to calculate cart total based in the sum of cart items, and cart items in the sum of selectable options, etc. The idea is to delegate the maths to each entity and get a total.

In the middle in the process, clients can modify some settings like quantities and because of that "caching" in _mutated I was unable to get the new total because that total was cached before in another checkout step. Also there is no method to clear "_mutated" array or doing something like that.

Finally, I transformed my protected _getTotal() methods in public calcTotal() methods to get the right total.

**Comment by lorenzo** [comment]
Is this with the latest cakephp (master branch)? We fixed a similar problem recently which should be out in a release soon.

**Comment by adayth** [comment]
3.0.4

**Comment by lorenzo** [comment]
ok, please wait for the 3.0.5 release of use master in the meantime.

**Comment by markstory** [comment]
I am hoping to get 3.0.5 out tonight :)

**Comment by adayth** [comment]
I still have issues with this after installing 3.0.5.

Code example to try to explain my issue a bit more:

Entities:
Cart has many CartItem
```
protected function _getTotal()
{
    $total = 0;
    foreach($this->cart_items as $cart_item) {
         $total += $cart_item->price;
    } 
    return $total;
}
```

If I add a CartItem to the Cart->cart_items, I need a mechanism to clear EntityTrait->_mutated. Is a similar issue with dirty and associations.
Notice that I can't clear _mutated inside _getTotal(), after first execution value is cached and never will get the updated value.

**Comment by lorenzo** [comment]
I really think this kind of calculating stuff cases are better handled by a custom method. The idea of properties is to have a kind of stable map of data you can use. A suggestion for the time being, while this is evaluated, is tonaleays set the array of items to the entity, instead of appending in-line.

**Comment by markstory** [comment]
@lorenzo does the mutated cache provide significant performance improvements  in apps you're working on?

**Comment by lorenzo** [comment]
@markstory Not that much, the main issue I was solving there was people doing lazy loading of associations. Without the cache it becomes much more difficult to handle. I think we could Remove the mutated cache and figure out another way of solving the lazy loading issue. Any ideas?

**Comment by markstory** [comment]
I think removing the mutated cache is probably the best option. Lazy loaded associations can be made easier through other means.

**Comment by adayth** [comment]
I like the idea of mutated cache, but to me the main problem is that I can't clear it if I wanted to do it nor disable it for any _getProperty()

Maybe a property to define "cached" and / or "not cached" _getProperty() methods should be enough.

Another idea is give control to developers with two or three simple methods like get / set / clean (MinimalCacheTrait?). So they can cache results easily if they wanted to do it in entity methods.

**Comment by markstory** [comment]
@adayth I'd rather we didn't have a cache if it needs more methods. The cache adds more complexity, and potential pitfalls for people to fall into. Having a simpler implementation still allows people who need the caching to implement it on the side.
